In [26]:
import numpy as np

x = np.array([12, 3, 6, 14])
print("x: ", x)
print(type(x))
print("x.ndim: ",x.ndim)
print("x.shape: ", x.shape)
print(x[0])
print(x[-2])

x:  [12  3  6 14]
<class 'numpy.ndarray'>
x.ndim:  1
x.shape:  (4,)
12
6


In [22]:
x = np.array([ [1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]
 ])
print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)
print(x[0,1])

x.ndim:  2
x.shape:  (3, 4)
2


In [23]:
x = np.array([
 [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32]]
 ])
print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)
print(x[0,1,2])

x.ndim:  3
x.shape:  (2, 3, 4)
7


In [29]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[3:8])
print(arr[3:11])
print(arr[3:8:2])
print(arr[3:-1])
print(arr[3:-3])
print(arr[3:])
print(arr[:5])
b = arr[3:8].copy()
print(arr)
print(b)
new = arr[3:8]
print(new)
new[0] = 33
print(new)
print(arr)

[3 4 5 6 7]
[ 3  4  5  6  7  8  9 10]
[3 5 7]
[3 4 5 6 7 8 9]
[3 4 5 6 7]
[ 3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7]
[3 4 5 6 7]
[33  4  5  6  7]
[ 0  1  2 33  4  5  6  7  8  9 10]


In [25]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
b = arr.reshape(3, 4)
print(b)
b = arr.reshape(2,2,3)
print(b)
b = arr.reshape(2,2,-1)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
